kind: Secret
apiVersion: v1
metadata:
  name: git-credentials
  labels:
    app: agrocd-trader-pipeline
    group: pipeline
    type: git
  annotations:
    build.openshift.io/source-secret-match-uri-1: 'https://github.com/*'
    tekton.dev/git-0: 'https://github.com'
data:
  password: gittoken
  username: username
type: kubernetes.io/basic-auth
